# WPV round selection for candidate fea3ce0a509ae54f669fb122bf1bf64e68cb1421 (generated; named MT proof tests only, CX-EXEC-014).
# Reuse basis: native non-live proof tests that passed in the 8ea13a9b validator union and whose test file is unchanged.
ROUND_SELECTION_SHA=fea3ce0a509ae54f669fb122bf1bf64e68cb1421
CORE_TESTS=(loom_daily_journal_tests loom_transclusion_tests loom_media_tiers_tests project_wiki_drift_tests loom_block_collection_views_tests)
CORE_FILTER='(binary_id(=handshake_core) & (test(=api::loom::tests::mt153_loom_route_family_authority_matrix) | test(=api::loom::tests::mounted_record_user_loom_creates_are_atomic_and_denied_writes_leave_no_rows) | test(=api::workspaces::tests::owned_workspace_delete_cascades_documents_versions_and_canvas_with_audit) | test(=api::workspaces::tests::mt109_c2_memory_surfaces_provisioned_and_process_routes_deny_by_default) | test(/^storage::surreal::mt136_database_surface_proof_(a|b|c)::/))) | binary_id(=handshake_core::loom_daily_journal_tests) | binary_id(=handshake_core::loom_transclusion_tests) | binary_id(=handshake_core::loom_media_tiers_tests) | binary_id(=handshake_core::project_wiki_drift_tests) | (binary_id(=handshake_core::loom_block_collection_views_tests) & (test(=table_sort_by_typed_column_is_correct_across_a_page_boundary) | test(=kanban_move_via_real_tag_edges_reflects_in_requery_and_embedded_store) | test(=free_kanban_places_shared_tag_cards_once_each) | test(=calendar_buckets_by_journal_date_with_date_filter) | test(=resort_persists_into_view_definition) | test(=saved_view_creation_is_idempotent_and_authority_backed)))'
NATIVE_TESTS=(test_author_id_budget test_block_collection_view test_canvas_board test_e7_knowledge_accesskit)
NATIVE_LIB=0
NATIVE_FILTER='(binary_id(=handshake-native::test_author_id_budget) & (test(=mt113_mounted_bookmark_remove_terminalizes_with_a_realistic_long_query))) | (binary_id(=handshake-native::test_block_collection_view) & (test(=block_collection_views_live_surrealdb_self_seed_full_round_trip))) | (binary_id(=handshake-native::test_canvas_board) & (test(=canvas_board_live_surrealdb_self_seeds_mounted_round_trip))) | binary_id(=handshake-native::test_e7_knowledge_accesskit)'
EXTRACTED_CRATES=()
