use std::{
    collections::BTreeMap,
    env, fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

const MT013_MANIFEST_NAME: &str = "mt013-compiled-worktree-manifest-v2.txt";

fn main() {
    // Ensure sqlx uses the prepared offline data by default; allow override via env.
    if std::env::var("SQLX_OFFLINE").is_err() {
        println!("cargo:rustc-env=SQLX_OFFLINE=true");
    }
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rerun-if-changed=src");
    write_mt013_compiled_worktree_manifest();
}

/// Build the MT-013 proof binary together with a deterministic manifest of
/// every tracked and untracked non-ignored worktree member. The manifest is
/// generated by this build script, embedded with `include_bytes!`, and compared
/// byte-for-byte with a freshly generated manifest at proof execution time.
/// No operator-supplied digest participates in the compile binding.
fn write_mt013_compiled_worktree_manifest() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let repo_root = discover_repo_root(&manifest_dir);
    let manifest = worktree_manifest(&repo_root);
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join(MT013_MANIFEST_NAME), manifest)
        .expect("write compile-derived MT-013 worktree manifest");

    // Directory watching is required in addition to member watching so a new
    // untracked, non-ignored source/config/lockfile also reruns this script.
    println!("cargo:rerun-if-changed={}", repo_root.display());
}

fn discover_repo_root(start: &Path) -> PathBuf {
    let mut candidate = start.to_path_buf();
    loop {
        if candidate.join(".git").exists() {
            return candidate;
        }
        assert!(candidate.pop(), "cannot discover worktree root");
    }
}

fn worktree_manifest(repo_root: &Path) -> Vec<u8> {
    let tracked_output = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["ls-files", "--cached", "--stage", "-v", "-z"])
        .output()
        .expect("git is required to enumerate tracked MT-013 compile closure members");
    assert!(
        tracked_output.status.success(),
        "git ls-files tracked enumeration failed during build: {}",
        String::from_utf8_lossy(&tracked_output.stderr)
    );
    let mut members = BTreeMap::<String, Option<TrackedIndexEntry>>::new();
    for entry in tracked_output
        .stdout
        .split(|byte| *byte == 0)
        .filter(|entry| !entry.is_empty())
    {
        let entry = String::from_utf8(entry.to_vec()).expect("tracked worktree path must be UTF-8");
        let (metadata, path) = entry.split_once('\t').unwrap_or_else(|| {
            panic!("malformed git ls-files --stage entry without tab: {entry:?}")
        });
        let mut fields = metadata.split_whitespace();
        let status_tag = fields
            .next()
            .and_then(|value| value.chars().next())
            .expect("tracked index status tag");
        let mode = fields.next().expect("tracked index mode").to_string();
        let index_object_id = fields.next().expect("tracked index object id").to_string();
        let stage = fields.next().expect("tracked index stage");
        assert_eq!(
            stage, "0",
            "MT-013 compile closure refuses unresolved index stage {stage} for {path}"
        );
        assert!(
            fields.next().is_none(),
            "unexpected index metadata for {path}"
        );
        let prior = members.insert(
            path.to_string(),
            Some(TrackedIndexEntry {
                status_tag,
                mode,
                index_object_id,
            }),
        );
        assert!(prior.is_none(), "duplicate tracked closure path {path}");
    }

    let untracked_output = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["ls-files", "--others", "--exclude-standard", "-z"])
        .output()
        .expect("git is required to enumerate untracked MT-013 compile closure members");
    assert!(
        untracked_output.status.success(),
        "git ls-files untracked enumeration failed during build: {}",
        String::from_utf8_lossy(&untracked_output.stderr)
    );
    for path in untracked_output
        .stdout
        .split(|byte| *byte == 0)
        .filter(|path| !path.is_empty())
    {
        let path = String::from_utf8(path.to_vec()).expect("untracked worktree path must be UTF-8");
        assert!(
            members.insert(path.clone(), None).is_none(),
            "path was both tracked and untracked: {path}"
        );
    }
    assert!(
        !members.is_empty(),
        "MT-013 compile closure must not be empty"
    );
    assert!(
        members
            .keys()
            .all(|path| !path.chars().any(|ch| matches!(ch, '\n' | '\r' | '\t'))),
        "MT-013 manifest paths must not contain control separators"
    );

    let mut present_paths = Vec::new();
    let mut absent_tracked = BTreeMap::new();
    for (path, tracked) in &members {
        let absolute = repo_root.join(path);
        match fs::symlink_metadata(&absolute) {
            Ok(_) if tracked.as_ref().is_some_and(|entry| entry.mode == "160000") => {
                absent_tracked.insert(path.clone(), "gitlink".to_string());
            }
            Ok(metadata) if metadata.is_file() || metadata.file_type().is_symlink() => {
                present_paths.push(path.clone());
            }
            Ok(_) => panic!(
                "MT-013 closure member is present but is not a file or symlink: {}",
                absolute.display()
            ),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => match tracked {
                Some(entry) if entry.mode == "160000" => {
                    absent_tracked.insert(path.clone(), "gitlink".to_string());
                }
                Some(entry) if matches!(entry.status_tag, 'S' | 's') => {
                    absent_tracked.insert(path.clone(), "skip-worktree".to_string());
                }
                Some(_) => panic!(
                    "MT-013 tracked closure member is absent without skip-worktree: {}",
                    absolute.display()
                ),
                None => panic!(
                    "MT-013 untracked closure member disappeared during enumeration: {}",
                    absolute.display()
                ),
            },
            Err(error) => panic!(
                "inspect MT-013 closure member {}: {error}",
                absolute.display()
            ),
        }
    }

    let mut hash_child = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["hash-object", "--no-filters", "--stdin-paths"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn git hash-object for MT-013 compile closure");
    let mut hash_input = Vec::new();
    for path in &present_paths {
        writeln!(&mut hash_input, "{path}").expect("write in-memory hash-object input");
    }
    let mut hash_stdin = hash_child.stdin.take().expect("hash-object stdin");
    let write_handle = std::thread::spawn(move || hash_stdin.write_all(&hash_input));
    let wait_result = hash_child.wait_with_output();
    let write_result = write_handle
        .join()
        .unwrap_or_else(|_| panic!("hash-object input writer thread panicked"));
    let hashes = wait_result.expect("wait for git hash-object");
    if let Err(write_error) = write_result {
        let first_disappeared = present_paths
            .iter()
            .find(|path| fs::symlink_metadata(repo_root.join(path)).is_err());
        panic!(
            "git hash-object input closed while hashing present MT-013 closure members; \
             first_disappeared={first_disappeared:?}; write_error={write_error}; stderr={}",
            String::from_utf8_lossy(&hashes.stderr)
        );
    }
    if !hashes.status.success() {
        let first_disappeared = present_paths
            .iter()
            .find(|path| fs::symlink_metadata(repo_root.join(path)).is_err());
        panic!(
            "git hash-object failed for present MT-013 closure members; \
             first_disappeared={first_disappeared:?}; status={}; stderr={}",
            hashes.status,
            String::from_utf8_lossy(&hashes.stderr)
        );
    }
    let object_ids = String::from_utf8(hashes.stdout)
        .expect("git object ids must be UTF-8")
        .lines()
        .map(str::to_owned)
        .collect::<Vec<_>>();
    assert_eq!(
        present_paths.len(),
        object_ids.len(),
        "manifest hash count drift for present closure members"
    );

    let present_object_ids = present_paths
        .iter()
        .cloned()
        .zip(object_ids)
        .collect::<BTreeMap<_, _>>();
    let mut manifest = b"hsk.mt013_compiled_worktree_manifest@2\n".to_vec();
    for (path, tracked) in &members {
        let absolute = repo_root.join(path);
        if let Some(absence_kind) = absent_tracked.get(path) {
            let tracked = tracked
                .as_ref()
                .expect("only tracked index entries may be explicitly absent");
            writeln!(
                &mut manifest,
                "A\t{absence_kind}\t{}\t{}\t{}\t{path}",
                tracked.status_tag, tracked.mode, tracked.index_object_id
            )
            .expect("write absent manifest row");
        } else {
            let object_id = present_object_ids
                .get(path)
                .expect("every present closure member has a worktree object id");
            let length = fs::symlink_metadata(&absolute)
                .unwrap_or_else(|error| panic!("inspect present {}: {error}", absolute.display()))
                .len();
            match tracked {
                Some(tracked) => writeln!(
                    &mut manifest,
                    "P\ttracked\t{}\t{}\t{}\t{path}\t{length}\t{object_id}",
                    tracked.status_tag, tracked.mode, tracked.index_object_id
                ),
                None => writeln!(
                    &mut manifest,
                    "P\tuntracked\t-\t-\t-\t{path}\t{length}\t{object_id}"
                ),
            }
            .expect("write present manifest row");
            println!("cargo:rerun-if-changed={}", absolute.display());
        }
    }
    manifest
}

struct TrackedIndexEntry {
    status_tag: char,
    mode: String,
    index_object_id: String,
}
