//! WP-KERNEL-009 MT-243 `WikiIncrementalIngestFanOut`.
//!
//! The Karpathy incremental-ingest loop: ONE changed source regenerates
//! exactly the pages whose MT-242 stamps cite it (set equality with the drift
//! result for that change — LM-PWIKI-010), refreshing each regenerated page's
//! wikilinks in the same pass, WITHOUT a full recompile. Fan-out is bounded by
//! an explicit budget; truncation leaves a LOUD EventLedger receipt and marks
//! the skipped pages stale — never silent (LM-PWIKI-011). Re-running a
//! completed fan-out is idempotent: the regenerated pages' stamps now match
//! current authority, the stale set resolves empty, and no duplicate
//! pages/links/receipts are produced.
//!
//! TRIGGER SURFACE (MT-243 handoff requirement):
//! * manual route — `POST /workspaces/:ws/loom/wiki/fanout` (api/loom.rs);
//! * ingest path — callers that re-index a source (e.g.
//!   `knowledge_code_index::engine` runs, document saves) invoke
//!   [`WikiFanOutEngine::run`] with the source's id after the authority write
//!   lands; the engine is deliberately NOT auto-wired into those writers so
//!   ingestion latency stays decoupled from wiki regeneration;
//! * drift path — `POST /workspaces/:ws/loom/wiki/drift-check` marks stale
//!   pages; operators/models then fan out per changed source.

use std::collections::{BTreeSet, HashMap};
use std::sync::Arc;

use serde_json::{json, Value};

use crate::storage::knowledge::{
    KnowledgeEntityKind, KnowledgeRebuildStatus, KnowledgeStore, KnowledgeWikiProjection,
};
use crate::storage::postgres::PostgresDatabase;

use super::compiler::{
    concept_page_title, render_concept_page, render_decision_page, render_entity_page,
    render_module_page, FileBundle, ModulePart, ProjectWikiCompiler, WikiCompileContext,
};
use super::{
    entity_content_hash, loom_block_state_content_hash, CitedSourceKind, WikiCompileError,
    WikiCompileResult, WikiCompileStamp, WikiPageType, DEFAULT_FANOUT_BUDGET, MAX_FANOUT_BUDGET,
};

/// One fan-out request: the changed source + the explicit budget.
#[derive(Clone, Debug)]
pub struct WikiFanOutRequest {
    pub source_kind: CitedSourceKind,
    pub source_id: String,
    /// Maximum pages regenerated this pass (clamped to
    /// 1..=[`MAX_FANOUT_BUDGET`]; default [`DEFAULT_FANOUT_BUDGET`]).
    pub budget: usize,
}

impl WikiFanOutRequest {
    pub fn new(source_kind: CitedSourceKind, source_id: impl Into<String>) -> Self {
        Self {
            source_kind,
            source_id: source_id.into(),
            budget: DEFAULT_FANOUT_BUDGET,
        }
    }
}

/// A page regenerated by the pass, with its per-page EventLedger receipt
/// (LM-PWIKI-012).
#[derive(Clone, Debug, serde::Serialize)]
pub struct WikiRegeneratedPage {
    pub projection_id: String,
    pub title: String,
    pub page_type: Option<String>,
    pub receipt_event_id: String,
}

/// A page identity (stale-set / truncation reporting).
#[derive(Clone, Debug, serde::Serialize)]
pub struct WikiPageRef {
    pub projection_id: String,
    pub title: String,
}

/// Outcome of one fan-out pass.
#[derive(Clone, Debug, serde::Serialize)]
pub struct WikiFanOutOutcome {
    pub workspace_id: String,
    pub trigger_kind: CitedSourceKind,
    pub trigger_id: String,
    /// The per-source stale set (pages citing the trigger whose stamped hash
    /// no longer matches authority) — MUST equal the MT-242 drift stale set
    /// for this change (LM-PWIKI-010; proven in tests).
    pub stale_set: Vec<WikiPageRef>,
    pub regenerated: Vec<WikiRegeneratedPage>,
    /// Budget-truncated pages (LOUD: receipted + left marked stale).
    pub truncated: Vec<WikiPageRef>,
    pub truncation_receipt_event_id: Option<String>,
    /// Pages whose cited record vanished from authority; regeneration cannot
    /// rebuild them — they stay stale until re-bootstrap or delete.
    pub orphaned: Vec<WikiPageRef>,
    pub index_refreshed: bool,
    pub started_receipt_event_id: String,
    pub completed_receipt_event_id: String,
    pub budget: usize,
    pub ledger_version: i64,
}

/// The MT-243 fan-out engine.
pub struct WikiFanOutEngine {
    db: Arc<PostgresDatabase>,
    compiler: ProjectWikiCompiler,
}

impl WikiFanOutEngine {
    pub fn new(db: Arc<PostgresDatabase>) -> Self {
        Self {
            compiler: ProjectWikiCompiler::new(db.clone()),
            db,
        }
    }

    /// Current content hash of ONE authority record (the trigger source).
    async fn current_hash(
        &self,
        workspace_id: &str,
        kind: CitedSourceKind,
        id: &str,
    ) -> WikiCompileResult<Option<String>> {
        Ok(match kind {
            CitedSourceKind::Source => self
                .db
                .get_wiki_source_hashes(std::slice::from_ref(&id.to_string()))
                .await?
                .remove(id),
            CitedSourceKind::Entity => self
                .db
                .get_wiki_entity_states(std::slice::from_ref(&id.to_string()))
                .await?
                .into_iter()
                .next()
                .map(|(entity, source_hash)| entity_content_hash(&entity, source_hash.as_deref())),
            CitedSourceKind::LoomBlock => self
                .db
                .get_wiki_loom_block_states(workspace_id, std::slice::from_ref(&id.to_string()))
                .await?
                .into_iter()
                .next()
                .map(|s| {
                    loom_block_state_content_hash(
                        s.title.as_deref(),
                        &s.content_type,
                        s.full_text_index.as_deref(),
                        s.document_id.as_deref(),
                        s.asset_id.as_deref(),
                        s.content_hash.as_deref(),
                    )
                }),
            CitedSourceKind::RichDocument => self
                .db
                .get_wiki_rich_document_hashes(std::slice::from_ref(&id.to_string()))
                .await?
                .remove(id),
        })
    }

    /// Run one fan-out pass for a changed source.
    pub async fn run(
        &self,
        ctx: &WikiCompileContext,
        workspace_id: &str,
        request: &WikiFanOutRequest,
    ) -> WikiCompileResult<WikiFanOutOutcome> {
        ctx.validate()?;
        if request.source_id.trim().is_empty() {
            return Err(WikiCompileError::Validation(
                "fan-out source_id is required".into(),
            ));
        }
        let budget = request.budget.clamp(1, MAX_FANOUT_BUDGET);
        let ledger_version = self.db.current_event_ledger_version().await?;

        // ---- the per-source stale set (LM-PWIKI-010 set equality) ----------
        // Pages whose stamps CITE the trigger…
        let candidates = self
            .db
            .list_knowledge_wiki_pages_citing(
                workspace_id,
                request.source_kind.as_str(),
                &request.source_id,
            )
            .await?;
        // …whose stamped hash for the trigger no longer matches authority.
        let current_hash = self
            .current_hash(workspace_id, request.source_kind, &request.source_id)
            .await?;
        let mut stale_pages: Vec<KnowledgeWikiProjection> = Vec::new();
        for page in candidates {
            let Some(stamp) = WikiCompileStamp::from_value(page.compile_stamp.as_ref()) else {
                continue;
            };
            let cited = stamp
                .cited_sources
                .iter()
                .find(|c| c.kind == request.source_kind && c.id == request.source_id);
            let Some(cited) = cited else { continue };
            let is_stale = match &current_hash {
                None => true, // cited record deleted from authority
                Some(hash) => hash != &cited.content_hash,
            };
            if is_stale {
                stale_pages.push(page);
            }
        }
        stale_pages.sort_by(|a, b| a.title.cmp(&b.title));
        let stale_set: Vec<WikiPageRef> = stale_pages
            .iter()
            .map(|p| WikiPageRef {
                projection_id: p.projection_id.clone(),
                title: p.title.clone(),
            })
            .collect();

        // ---- started receipt -------------------------------------------------
        let started_receipt_event_id = self
            .compiler
            .append_receipt(
                ctx,
                workspace_id,
                None,
                json!({
                    "kind": "wiki_fanout_started",
                    "workspace_id": workspace_id,
                    "trigger": {"kind": request.source_kind.as_str(), "id": request.source_id},
                    "trigger_current_hash": current_hash,
                    "stale_set": stale_set,
                    "budget": budget,
                    "ledger_version": ledger_version,
                }),
            )
            .await?;

        // ---- budget split (LOUD truncation, LM-PWIKI-011) --------------------
        let (to_regenerate, to_truncate) = if stale_pages.len() > budget {
            let truncated = stale_pages.split_off(budget);
            (stale_pages, truncated)
        } else {
            (stale_pages, Vec::new())
        };

        // ---- run-level link context (rebuilt once, reused per page) ----------
        let link_context = self.build_link_context(workspace_id).await?;

        // ---- regenerate exactly the (budgeted) stale set ----------------------
        let mut regenerated: Vec<WikiRegeneratedPage> = Vec::new();
        let mut orphaned: Vec<WikiPageRef> = Vec::new();
        for page in &to_regenerate {
            match self
                .regenerate_page(
                    ctx,
                    workspace_id,
                    page,
                    &link_context,
                    ledger_version,
                    &started_receipt_event_id,
                    request,
                )
                .await?
            {
                Some(entry) => regenerated.push(entry),
                None => orphaned.push(WikiPageRef {
                    projection_id: page.projection_id.clone(),
                    title: page.title.clone(),
                }),
            }
        }

        // ---- truncation: receipt + persistent stale marks (never silent) ------
        let mut truncation_receipt_event_id = None;
        if !to_truncate.is_empty() {
            let skipped: Vec<WikiPageRef> = to_truncate
                .iter()
                .map(|p| WikiPageRef {
                    projection_id: p.projection_id.clone(),
                    title: p.title.clone(),
                })
                .collect();
            for page in &to_truncate {
                self.db
                    .set_knowledge_projection_rebuild_status(
                        &page.projection_id,
                        KnowledgeRebuildStatus::Stale,
                    )
                    .await?;
            }
            let receipt_id = self
                .compiler
                .append_receipt(
                    ctx,
                    workspace_id,
                    Some(&started_receipt_event_id),
                    json!({
                        "kind": "wiki_fanout_truncated",
                        "workspace_id": workspace_id,
                        "trigger": {"kind": request.source_kind.as_str(), "id": request.source_id},
                        "budget": budget,
                        "total_stale": stale_set.len(),
                        "regenerated": regenerated.len(),
                        "skipped": skipped,
                    }),
                )
                .await?;
            truncation_receipt_event_id = Some(receipt_id);
        }

        // ---- same-pass index + link refresh ------------------------------------
        let mut index_refreshed = false;
        if !regenerated.is_empty() {
            self.compiler
                .compile_index_page(workspace_id, ledger_version, &started_receipt_event_id)
                .await?;
            index_refreshed = true;
            // Resolve title-only wikilinks on the regenerated pages (backlink
            // refresh in the same pass — wholesale replacement, idempotent).
            let mut fresh_rows = Vec::new();
            for entry in &regenerated {
                if let Some(row) = self
                    .db
                    .get_knowledge_wiki_projection(&entry.projection_id)
                    .await?
                {
                    fresh_rows.push(row);
                }
            }
            self.compiler
                .resolve_page_links(workspace_id, &mut fresh_rows)
                .await?;
        }

        // ---- completed receipt --------------------------------------------------
        let completed_receipt_event_id = self
            .compiler
            .append_receipt(
                ctx,
                workspace_id,
                Some(&started_receipt_event_id),
                json!({
                    "kind": "wiki_fanout_completed",
                    "workspace_id": workspace_id,
                    "trigger": {"kind": request.source_kind.as_str(), "id": request.source_id},
                    "stale_set": stale_set,
                    "regenerated": regenerated,
                    "truncated": to_truncate.len(),
                    "orphaned": orphaned,
                    "index_refreshed": index_refreshed,
                    "budget": budget,
                    "ledger_version": ledger_version,
                }),
            )
            .await?;

        Ok(WikiFanOutOutcome {
            workspace_id: workspace_id.to_string(),
            trigger_kind: request.source_kind,
            trigger_id: request.source_id.clone(),
            stale_set,
            regenerated,
            truncated: to_truncate
                .iter()
                .map(|p| WikiPageRef {
                    projection_id: p.projection_id.clone(),
                    title: p.title.clone(),
                })
                .collect(),
            truncation_receipt_event_id,
            orphaned,
            index_refreshed,
            started_receipt_event_id,
            completed_receipt_event_id,
            budget,
            ledger_version,
        })
    }

    /// Run-level navigation context: the current module-part layout (for link
    /// targets) and the source→dir dependency map.
    async fn build_link_context(&self, workspace_id: &str) -> WikiCompileResult<LinkContext> {
        let pages = self
            .db
            .list_knowledge_wiki_pages(workspace_id, None, true, 2_000, 0)
            .await?;
        let mut parts: Vec<ModulePart> = Vec::new();
        let mut concept_dirs: BTreeSet<String> = BTreeSet::new();
        for page in &pages {
            let Some(recipe) = &page.compile_recipe else {
                continue;
            };
            match recipe.get("kind").and_then(|k| k.as_str()) {
                Some("module") => {
                    let dir = recipe
                        .get("dir")
                        .and_then(|d| d.as_str())
                        .unwrap_or("(root)")
                        .to_string();
                    let part = recipe.get("part").and_then(|p| p.as_u64()).unwrap_or(1) as usize;
                    let total_parts = recipe
                        .get("total_parts")
                        .and_then(|p| p.as_u64())
                        .unwrap_or(1) as usize;
                    // Link-target shells: title() needs dir/part/total only.
                    parts.push(ModulePart {
                        dir,
                        part,
                        total_parts,
                        files: Vec::new(),
                    });
                }
                Some("concept") => {
                    if let Some(dir) = recipe.get("dir").and_then(|d| d.as_str()) {
                        concept_dirs.insert(dir.to_string());
                    }
                }
                _ => {}
            }
        }
        // source_id -> dir map + cross-module dependency edges.
        let inputs = self.db.list_wiki_code_file_inputs(workspace_id).await?;
        let source_dir: HashMap<String, String> = inputs
            .iter()
            .map(|i| {
                (
                    i.source_id.clone(),
                    super::compiler::cluster_dir(&i.relative_path),
                )
            })
            .collect();
        let edges = self
            .db
            .list_wiki_cross_source_code_edges(workspace_id, 100_000)
            .await?;
        let mut dir_deps: HashMap<String, BTreeSet<String>> = HashMap::new();
        for edge in &edges {
            if let (Some(from), Some(to)) = (
                source_dir.get(&edge.from_source_id),
                source_dir.get(&edge.to_source_id),
            ) {
                if from != to {
                    dir_deps
                        .entry(from.clone())
                        .or_default()
                        .insert(to.clone());
                }
            }
        }
        Ok(LinkContext {
            parts,
            concept_dirs,
            dir_deps,
        })
    }

    /// Regenerate ONE page from its compile recipe against CURRENT authority.
    /// Returns `None` when the cited record vanished (orphaned page).
    #[allow(clippy::too_many_arguments)]
    async fn regenerate_page(
        &self,
        ctx: &WikiCompileContext,
        workspace_id: &str,
        page: &KnowledgeWikiProjection,
        link_context: &LinkContext,
        ledger_version: i64,
        causation_receipt_id: &str,
        request: &WikiFanOutRequest,
    ) -> WikiCompileResult<Option<WikiRegeneratedPage>> {
        let recipe = page.compile_recipe.clone().unwrap_or_else(|| json!({}));
        let recipe_kind = recipe
            .get("kind")
            .and_then(|k| k.as_str())
            .unwrap_or("")
            .to_string();

        // Per-page regeneration receipt FIRST (the row's
        // rebuild_receipt_event_id FK target), idempotency key scoped to this
        // run via the started receipt's causation chain.
        let receipt_event_id = self
            .compiler
            .append_receipt(
                ctx,
                workspace_id,
                Some(causation_receipt_id),
                json!({
                    "kind": "wiki_page_fanout_regenerated",
                    "workspace_id": workspace_id,
                    "projection_id": page.projection_id,
                    "title": page.title,
                    "page_type": page.page_type,
                    "recipe_kind": recipe_kind,
                    "trigger": {"kind": request.source_kind.as_str(), "id": request.source_id},
                    "ledger_version": ledger_version,
                }),
            )
            .await?;

        let regenerated = match recipe_kind.as_str() {
            "module" => {
                let dir = recipe
                    .get("dir")
                    .and_then(|d| d.as_str())
                    .unwrap_or("(root)")
                    .to_string();
                let part = recipe.get("part").and_then(|p| p.as_u64()).unwrap_or(1) as usize;
                let total_parts = recipe
                    .get("total_parts")
                    .and_then(|p| p.as_u64())
                    .unwrap_or(1) as usize;
                let source_ids = recipe_source_ids(&recipe);
                let bundles = self.load_bundles(workspace_id, &source_ids).await?;
                if bundles.is_empty() {
                    return Ok(None); // every cited file vanished — orphan
                }
                let module_part = ModulePart {
                    dir: dir.clone(),
                    part,
                    total_parts,
                    files: bundles,
                };
                let dep_dirs = link_context.dir_deps.get(&dir).cloned().unwrap_or_default();
                let has_concept_page = link_context.concept_dirs.contains(&dir);
                let (rendered, citations, links) = render_module_page(
                    &module_part,
                    &dep_dirs,
                    has_concept_page,
                    &link_context.parts,
                );
                Some(
                    self.compiler
                        .upsert_page(
                            workspace_id,
                            &page.title,
                            WikiPageType::Module,
                            rendered,
                            citations,
                            recipe.clone(),
                            links,
                            ledger_version,
                            &receipt_event_id,
                        )
                        .await?,
                )
            }
            "concept" => {
                let dir = recipe
                    .get("dir")
                    .and_then(|d| d.as_str())
                    .unwrap_or("(root)")
                    .to_string();
                let source_ids = recipe_source_ids(&recipe);
                let bundles = self.load_bundles(workspace_id, &source_ids).await?;
                if bundles.is_empty() {
                    return Ok(None);
                }
                let (rendered, citations, links) =
                    render_concept_page(&dir, &bundles, &link_context.parts);
                // Keep the canonical concept title derived from the dir (the
                // page identity), not a possibly drifted stored title.
                let title = concept_page_title(&dir);
                Some(
                    self.compiler
                        .upsert_page(
                            workspace_id,
                            &title,
                            WikiPageType::Concept,
                            rendered,
                            citations,
                            recipe.clone(),
                            links,
                            ledger_version,
                            &receipt_event_id,
                        )
                        .await?,
                )
            }
            "entity" => {
                let document_id = recipe
                    .get("rich_document_id")
                    .and_then(|d| d.as_str())
                    .unwrap_or("");
                match self.db.get_knowledge_rich_document(document_id).await? {
                    Some(document) => {
                        let (title, rendered, citations, links) = render_entity_page(&document);
                        Some(
                            self.compiler
                                .upsert_page(
                                    workspace_id,
                                    &title,
                                    WikiPageType::Entity,
                                    rendered,
                                    citations,
                                    recipe.clone(),
                                    links,
                                    ledger_version,
                                    &receipt_event_id,
                                )
                                .await?,
                        )
                    }
                    None => None,
                }
            }
            "decision" => {
                let entity_id = recipe
                    .get("entity_id")
                    .and_then(|d| d.as_str())
                    .unwrap_or("");
                let states = self
                    .db
                    .get_wiki_entity_states(std::slice::from_ref(&entity_id.to_string()))
                    .await?;
                match states.into_iter().next() {
                    Some((entity, source_hash)) => {
                        let (title, rendered, citations, links) =
                            render_decision_page(&entity, source_hash.as_deref());
                        Some(
                            self.compiler
                                .upsert_page(
                                    workspace_id,
                                    &title,
                                    WikiPageType::Decision,
                                    rendered,
                                    citations,
                                    recipe.clone(),
                                    links,
                                    ledger_version,
                                    &receipt_event_id,
                                )
                                .await?,
                        )
                    }
                    None => None,
                }
            }
            "index" => Some(
                self.compiler
                    .compile_index_page(workspace_id, ledger_version, &receipt_event_id)
                    .await?,
            ),
            // MT-184 operator topic pages cite Loom blocks; their regenerate
            // path re-renders + RE-STAMPS through the storage compile
            // (`compile_loom_wiki_projection`).
            "loom_topic" => {
                use crate::storage::Database;
                let refreshed = self
                    .db
                    .regenerate_loom_wiki_projection(workspace_id, &page.projection_id)
                    .await?;
                return Ok(Some(WikiRegeneratedPage {
                    projection_id: refreshed.projection_id,
                    title: refreshed.title,
                    page_type: refreshed.page_type,
                    receipt_event_id,
                }));
            }
            other => {
                return Err(WikiCompileError::Validation(format!(
                    "page {} has no regenerable compile recipe (kind '{other}')",
                    page.projection_id
                )));
            }
        };

        Ok(regenerated.map(|row| WikiRegeneratedPage {
            projection_id: row.projection_id,
            title: row.title,
            page_type: row.page_type,
            receipt_event_id,
        }))
    }

    /// Load current file bundles (input + symbols + concepts) for a recipe's
    /// source set. Vanished sources are silently dropped from the PAGE (their
    /// absence is visible in the regenerated citations + receipt).
    async fn load_bundles(
        &self,
        workspace_id: &str,
        source_ids: &[String],
    ) -> WikiCompileResult<Vec<FileBundle>> {
        let inputs = self
            .db
            .list_wiki_code_file_inputs_by_sources(workspace_id, source_ids)
            .await?;
        let mut bundles = Vec::with_capacity(inputs.len());
        for input in inputs {
            let symbols = self
                .db
                .list_wiki_source_entities_with_spans(
                    workspace_id,
                    &input.source_id,
                    KnowledgeEntityKind::Symbol,
                )
                .await?;
            let concepts = self
                .db
                .list_wiki_source_entities_with_spans(
                    workspace_id,
                    &input.source_id,
                    KnowledgeEntityKind::Concept,
                )
                .await?;
            bundles.push(FileBundle {
                input,
                symbols,
                concepts,
            });
        }
        Ok(bundles)
    }
}

/// Run-level navigation/link context (built once per fan-out pass).
struct LinkContext {
    parts: Vec<ModulePart>,
    concept_dirs: BTreeSet<String>,
    dir_deps: HashMap<String, BTreeSet<String>>,
}

fn recipe_source_ids(recipe: &Value) -> Vec<String> {
    recipe
        .get("source_ids")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect()
        })
        .unwrap_or_default()
}
