use super::types::{
    CommandReference, CommandStatus, Manual, ManualFeatureGroup, ManualSafetyConstraint,
    ManualWorkflow,
};
use super::MANUAL_VERSION;

pub static MODEL_MANUAL: Manual = Manual {
    version: MANUAL_VERSION,
    feature_groups: FEATURE_GROUPS,
    command_reference: COMMAND_REFERENCE,
    safety_constraints: SAFETY_CONSTRAINTS,
    workflows: WORKFLOWS,
};

pub fn model_manual() -> &'static Manual {
    &MODEL_MANUAL
}

pub static FEATURE_GROUPS: &[ManualFeatureGroup] = &[
    ManualFeatureGroup {
        id: "hbr_process_diagnostics",
        title: "HBR, Process Ledger, And Diagnostics",
        description: "Build-rule enforcement, typed violation receipts, process lifecycle evidence, and no-context diagnostics entrypoints.",
        commands: &[
            "model_manual_get",
            "model_manual_list_commands",
            "model_manual_search",
            "hbr_violation_emit",
            "hbr_matrix_check",
            "hbr_validator_scan",
            "process_ledger_writer",
            "process_ledger_overflow_event",
            "process_ledger_reclaim",
            "process_ledger_staleness_reclaim",
            "diagnostics_capture_headless",
            "visual_debug_dom_snapshot",
            "visual_debug_console_stream_start",
            "visual_debug_console_stream_stop",
            "backend_inspector_read",
            "kernel_inspector_port",
            "kernel_inspector_list_sessions",
            "kernel_inspector_session_state",
            "kernel_inspector_event_ledger_tail",
            "kernel_inspector_process_ledger_active",
            "kernel_inspector_trace_projection",
            "kernel_inspector_loaded_models",
            "inspector_replay_drive",
            "swarm_harness_run",
            "handshake_swarm_cli",
            "kernel_swarm_run",
            "swarm_scenario_n8_perf",
            "swarm_scenario_session_cancel",
            "swarm_scenario_lease_contention",
        ],
    },
    ManualFeatureGroup {
        id: "sandbox",
        title: "Sandbox",
        description: "KERNEL-004 sandbox adapter surfaces for boxed model-written code and validation runners.",
        commands: &["sandbox_adapter_run", "sandbox_adapter_health"],
    },
    ManualFeatureGroup {
        id: "model_runtime",
        title: "Model Runtime",
        description: "Local model registration, generation, LoRA hot-swap, KV cache controls, and inference-lab technique switches.",
        commands: &[
            "model_runtime_generate",
            "model_runtime_register_model",
            "inference_lab_apply_technique",
        ],
    },
    ManualFeatureGroup {
        id: "memory_self_improvement",
        title: "Memory And Self Improvement",
        description: "Memory capsule retrieval, distillation candidates, and bounded self-improvement loop controls.",
        commands: &[
            "memory_capsule_build",
            "memory_calibration_snapshot",
            "self_improvement_run_iteration",
            "distillation_candidate_review",
        ],
    },
];

pub static COMMAND_REFERENCE: &[CommandReference] = &[
    CommandReference {
        id: "model_manual_get",
        name: "model_manual_get",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.model_manual.get"),
        tauri_command: Some("model_manual_get"),
        schema_fields: &[
            "version",
            "feature_groups",
            "command_reference",
            "safety_constraints",
            "workflows",
        ],
        cli_flag: None,
        description: "Return the full typed ModelManual manifest as JSON for an in-app or no-context model reader.",
        expected_input: "No input.",
        expected_output: "Manual JSON containing version, feature groups, command references, safety constraints, and workflows.",
        common_errors: &[
            "IPC bridge not registered",
            "manual projection consumer expects stale field names",
        ],
        recovery_steps: &[
            "Check MANUAL_VERSION and the MT-013 IPC bridge registration",
            "Use model_manual_list_commands to inspect the current command index",
        ],
    },
    CommandReference {
        id: "model_manual_list_commands",
        name: "model_manual_list_commands",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.model_manual.list_commands"),
        tauri_command: Some("model_manual_list_commands"),
        schema_fields: &["id", "name", "status", "ipc_channel", "tauri_command"],
        cli_flag: None,
        description: "Return the command reference index without the long workflow and recovery text.",
        expected_input: "No input.",
        expected_output: "CommandReference summary rows keyed by stable command id.",
        common_errors: &["Command id not found in a feature group"],
        recovery_steps: &["Run model_manual_tests to verify feature group references resolve"],
    },
    CommandReference {
        id: "model_manual_search",
        name: "model_manual_search",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.model_manual.search"),
        tauri_command: Some("model_manual_search"),
        schema_fields: &["query", "results", "command_id", "workflow_id"],
        cli_flag: None,
        description: "Search command, workflow, safety, and feature group text by substring.",
        expected_input: "A non-empty query string.",
        expected_output: "Search results referencing command ids, workflow ids, and safety constraint ids.",
        common_errors: &[
            "Empty query",
            "manual data not loaded through the IPC bridge",
        ],
        recovery_steps: &[
            "Call model_manual_get for the full manifest",
            "Retry with a concrete command, workflow, or HBR id",
        ],
    },
    CommandReference {
        id: "hbr_violation_emit",
        name: "hbr_violation_emit",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "receipt_kind",
            "schema_version",
            "receipt_uuid",
            "hbr_id",
            "wp_id",
            "violation_class",
        ],
        cli_flag: Some("--self-test"),
        description: "Emit or validate canonical HBR_VIOLATION JSONL receipts for build-time and handoff-time routing.",
        expected_input: "An HBR_VIOLATION object or self-test flag.",
        expected_output: "Sorted-key UTF-8 JSONL receipt with a UUID v7 receipt_uuid.",
        common_errors: &[
            "Unknown violation_class",
            "receipt_uuid is not UUID v7",
            "freeform notes used as routing data",
        ],
        recovery_steps: &[
            "Validate against hbr-violation.schema.json",
            "Rebuild the receipt from typed HBR fields instead of notes text",
        ],
    },
    CommandReference {
        id: "hbr_matrix_check",
        name: "hbr_matrix_check",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "acceptance_matrix",
            "hbr",
            "hbr_not_applicable",
            "evidence_pointer",
            "validator_verdict",
        ],
        cli_flag: Some("--all-packets"),
        description: "Verify PACKET_ACCEPTANCE_MATRIX HBR rows block PASS closure when any row remains PENDING, STEER, or BLOCKED.",
        expected_input: "A packet path or all-packets mode.",
        expected_output: "Exit 0 on pass; JSONL failures on matrix violations.",
        common_errors: &[
            "PROVED row has no evidence_pointer",
            "NOT_APPLICABLE row lacks a ledger reason",
        ],
        recovery_steps: &[
            "Hydrate the matrix from HANDSHAKE_BUILD_RULES",
            "Attach runnable evidence or not-applicable reasons",
        ],
    },
    CommandReference {
        id: "hbr_validator_scan",
        name: "hbr_validator_scan",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "evidence_pointer",
            "hbr_evidence_results",
            "hbr_event_ledger",
        ],
        cli_flag: Some("--packet"),
        description: "Resolve PROVED HBR evidence pointers to tests, receipts, artifacts, or EventLedger rows.",
        expected_input: "A work-packet JSON file with HBR matrix rows.",
        expected_output: "Exit 0 when PROVED evidence resolves; downgraded STEER rows written atomically otherwise.",
        common_errors: &[
            "Unknown evidence URI scheme",
            "test evidence has no recorded PASS result",
        ],
        recovery_steps: &[
            "Use test://, receipt://, artifact://, or event:// pointers",
            "Record the passing proof result before claiming PROVED",
        ],
    },
    CommandReference {
        id: "process_ledger_writer",
        name: "process_ledger_writer",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "process_uuid",
            "engine_kind",
            "started_at",
            "stopped_at",
            "exit_code",
            "owner_role",
            "owner_wp",
        ],
        cli_flag: None,
        description: "Append START and STOP process lifecycle events through the bounded ProcessOwnershipLedger writer.",
        expected_input: "Typed ProcessStart and ProcessStop records from model engines, sandbox containers, workers, plugins, or helper subprocesses.",
        expected_output: "Postgres kernel_process_lifecycle rows with UUID v7 process_uuid values and matched lifecycle timestamps.",
        common_errors: &[
            "Writer channel saturated",
            "STOP arrives after START overflow",
            "Postgres lifecycle migration missing",
        ],
        recovery_steps: &[
            "Inspect FR_EVT_LEDGER_OVERFLOW events",
            "Use the STOP upsert path to preserve termination evidence",
            "Apply migration 0021_kernel_process_lifecycle.sql",
        ],
    },
    CommandReference {
        id: "process_ledger_overflow_event",
        name: "process_ledger_overflow_event",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "event_type",
            "overflow_count",
            "capacity",
            "dropped_event_kind",
            "sampled_event_payload",
        ],
        cli_flag: None,
        description: "Emit typed FR_EVT_LEDGER_OVERFLOW EventLedger rows when the process lifecycle writer channel saturates.",
        expected_input: "A dropped LedgerEvent sampled from a full bounded channel.",
        expected_output: "FR_EVT_LEDGER_OVERFLOW NewKernelEvent payload with overflow count, configured capacity, dropped event kind, and sampled lifecycle payload.",
        common_errors: &[
            "Overflow sink unavailable",
            "sampled payload lacks process_uuid",
            "degraded flag not cleared after drain",
        ],
        recovery_steps: &[
            "Verify the overflow sink records the event before returning Ok",
            "Drain queued lifecycle events",
            "Confirm process_ledger::is_degraded() returns false after a successful drain",
        ],
    },
    CommandReference {
        id: "process_ledger_reclaim",
        name: "process_ledger_reclaim",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "session_id",
            "trigger",
            "processes_reclaimed",
            "kill_result",
            "total_duration_ms",
        ],
        cli_flag: None,
        description: "Reclaim open process lifecycle rows on session close, failure, staleness, or operator cancel.",
        expected_input: "A session id and ReclaimTrigger value: close, failure, stale, or operator_cancel.",
        expected_output: "ReclaimReport with every reclaimed process, kill result, and queued STOP evidence using exit_code -1.",
        common_errors: &[
            "SandboxKill binding missing",
            "kill returns an error",
            "STOP writer channel saturated",
        ],
        recovery_steps: &[
            "Treat kill errors as report data, not as permission to skip STOP",
            "Verify the STOP writer accepted ProcessStop rows",
            "Inspect kernel_process_lifecycle open rows with the reclaim FOR UPDATE query",
        ],
    },
    CommandReference {
        id: "process_ledger_staleness_reclaim",
        name: "process_ledger_staleness_reclaim",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &["ttl", "scan_interval", "stale_sessions", "trigger"],
        cli_flag: None,
        description: "Run the background staleness reclaim loop with a configurable heartbeat TTL and scan interval.",
        expected_input: "StalenessReclaimConfig plus a stale-session source.",
        expected_output: "Background task that calls process_ledger_reclaim with trigger stale for each stale session.",
        common_errors: &[
            "TTL configured as zero",
            "scan interval configured as zero",
            "stale source fails",
        ],
        recovery_steps: &[
            "Use the 5 minute default TTL when unset",
            "Use the 30 second default scan interval when unset",
            "Keep stale-source failures isolated to the current scan tick",
        ],
    },
    CommandReference {
        id: "diagnostics_capture_headless",
        name: "diagnostics_capture_headless",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.diagnostics.capture"),
        tauri_command: Some("diagnostics_capture_headless"),
        schema_fields: &[
            "viewport",
            "selector",
            "screenshot_ref",
            "console_events",
            "network_events",
        ],
        cli_flag: None,
        description: "Capture GUI state, screenshots, console events, and network events without stealing operator focus.",
        expected_input: "A target route, viewport, and optional selector.",
        expected_output: "Diagnostic capture artifact references and replay metadata.",
        common_errors: &[
            "Target route not mounted",
            "foreground window requested during model-driven testing",
        ],
        recovery_steps: &[
            "Use hidden-window/headless mode",
            "Open the diagnostics panel replay for the failed step",
        ],
    },
    CommandReference {
        id: "visual_debug_dom_snapshot",
        name: "kernel_visual_debug_dom_snapshot",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.visual_debug.dom_snapshot"),
        tauri_command: Some("kernel_visual_debug_dom_snapshot"),
        schema_fields: &[
            "kind",
            "selector",
            "root",
            "node_id",
            "node_name",
            "attributes",
            "children",
            "stable_element_id",
        ],
        cli_flag: None,
        description: "Return a CDP DOM.getDocument or selector-scoped DOM.describeNode snapshot for diagnostics without foreground interaction.",
        expected_input: "DomScope JSON: { kind: 'full' } or { kind: 'selector', selector: '<css selector>' }.",
        expected_output: "DomTree JSON with owned nodes, attributes, children, and stable_element_id populated only from data-testid.",
        common_errors: &[
            "WebView2 CDP port unavailable",
            "selector did not match any element",
            "CDP DOM response omitted node data",
        ],
        recovery_steps: &[
            "Check kernel_visual_debug_launch_config for the active CDP port",
            "Retry with a data-testid selector from the current route",
            "Use the screenshot command to confirm the renderer loaded before snapshotting",
        ],
    },
    CommandReference {
        id: "visual_debug_console_stream_start",
        name: "kernel_visual_debug_console_stream_start",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.visual_debug.console_stream.start"),
        tauri_command: Some("kernel_visual_debug_console_stream_start"),
        schema_fields: &[
            "stream_id",
            "kind",
            "level",
            "message",
            "timestamp",
            "stack",
        ],
        cli_flag: None,
        description: "Start a WebView2 CDP Runtime console/exception stream and emit console_event payloads to the diagnostics panel.",
        expected_input: "ConsoleScope JSON: { kind: 'all' }.",
        expected_output: "Object containing a UUID v7 stream_id; subsequent console_event payloads contain stream_id, kind, message, timestamp, and optional stack.",
        common_errors: &[
            "WebView2 CDP port unavailable",
            "CDP Runtime.enable failed",
            "diagnostics event listener not registered",
        ],
        recovery_steps: &[
            "Check kernel_visual_debug_launch_config for the active CDP port",
            "Restart the stream and subscribe to console_event before injecting diagnostics actions",
        ],
    },
    CommandReference {
        id: "visual_debug_console_stream_stop",
        name: "kernel_visual_debug_console_stream_stop",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.visual_debug.console_stream.stop"),
        tauri_command: Some("kernel_visual_debug_console_stream_stop"),
        schema_fields: &["stream_id", "stopped"],
        cli_flag: None,
        description: "Stop a running WebView2 CDP Runtime console/exception stream and unregister its in-memory task handle.",
        expected_input: "The stream_id returned by kernel_visual_debug_console_stream_start.",
        expected_output: "Object with stopped flag indicating whether a matching stream was found and aborted.",
        common_errors: &[
            "Unknown stream_id",
            "stream already stopped",
            "console stream registry unavailable",
        ],
        recovery_steps: &[
            "Treat false stopped as idempotent cleanup",
            "Start a fresh stream before the next visual diagnostics capture",
        ],
    },
    CommandReference {
        id: "backend_inspector_read",
        name: "backend_inspector_read",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.inspector.read"),
        tauri_command: Some("backend_inspector_read"),
        schema_fields: &["surface", "selector", "state_snapshot", "trace_id"],
        cli_flag: None,
        description: "Read structured backend state for model navigation without screen scraping.",
        expected_input: "An inspector surface id and optional selector.",
        expected_output: "Structured state snapshot with stable ids and trace references.",
        common_errors: &[
            "Unknown inspector surface",
            "state snapshot exceeds configured budget",
        ],
        recovery_steps: &[
            "List available inspector surfaces",
            "Narrow the selector before retrying",
        ],
    },
    CommandReference {
        id: "kernel_inspector_port",
        name: "kernel_inspector_port",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.port"),
        tauri_command: Some("kernel_inspector_port"),
        schema_fields: &["port"],
        cli_flag: None,
        description: "Return the optional local inspector HTTP port exposed to diagnostics tooling.",
        expected_input: "No input.",
        expected_output: "InspectorReadV1-adjacent port response: the current random local inspector port, or null when the HTTP inspector is not running.",
        common_errors: &[
            "Inspector port state is not registered",
            "inspector port state mutex poisoned",
        ],
        recovery_steps: &[
            "Verify Tauri Builder manages InspectorPortState",
            "Fall back to in-process kernel.inspector.* IPC commands when no port is running",
        ],
    },
    CommandReference {
        id: "kernel_inspector_list_sessions",
        name: "kernel_inspector_list_sessions",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.list_sessions"),
        tauri_command: Some("kernel_inspector_list_sessions"),
        schema_fields: &["id", "state", "model_id", "active_process_count"],
        cli_flag: None,
        description: "Read all visible inspector sessions through the in-process InspectorReadV1 trait.",
        expected_input: "No input.",
        expected_output: "InspectorReadV1 SessionSummary rows serialized for Diagnostics-panel navigation.",
        common_errors: &[
            "InspectorReadV1 state is not registered",
            "session list is empty before a governed run starts",
        ],
        recovery_steps: &[
            "Verify Tauri Builder manages Arc<dyn InspectorReadV1>",
            "Start or resume a governed session before expecting active rows",
        ],
    },
    CommandReference {
        id: "kernel_inspector_session_state",
        name: "kernel_inspector_session_state",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.session_state"),
        tauri_command: Some("kernel_inspector_session_state"),
        schema_fields: &[
            "session_id",
            "id",
            "state",
            "latest_event_id",
            "active_process_count",
        ],
        cli_flag: None,
        description: "Read a single session state by SessionId through the in-process InspectorReadV1 trait.",
        expected_input: "A SessionId for the governed model session.",
        expected_output: "InspectorReadV1 SessionStateRead JSON or null when the session is unknown.",
        common_errors: &[
            "Unknown session_id",
            "InspectorReadV1 state is not registered",
        ],
        recovery_steps: &[
            "Call kernel_inspector_list_sessions to discover valid ids",
            "Confirm the diagnostics panel is attached to the current app process",
        ],
    },
    CommandReference {
        id: "kernel_inspector_event_ledger_tail",
        name: "kernel_inspector_event_ledger_tail",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.event_ledger_tail"),
        tauri_command: Some("kernel_inspector_event_ledger_tail"),
        schema_fields: &[
            "n",
            "event_id",
            "event_type",
            "event_sequence",
            "created_at_utc",
            "payload_hash",
            "payload",
        ],
        cli_flag: None,
        description: "Read the newest EventLedger rows through the in-process InspectorReadV1 trait without using the HTTP server.",
        expected_input: "A non-negative tail limit n.",
        expected_output: "InspectorReadV1 EventLedgerRow JSON ordered by the reader implementation's tail semantics.",
        common_errors: &[
            "Tail limit is too small to include the needed event",
            "InspectorReadV1 state is not registered",
        ],
        recovery_steps: &[
            "Increase n for the diagnostic query",
            "Use kernel_inspector_trace_projection for session-scoped reconstruction",
        ],
    },
    CommandReference {
        id: "kernel_inspector_process_ledger_active",
        name: "kernel_inspector_process_ledger_active",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.process_ledger_active"),
        tauri_command: Some("kernel_inspector_process_ledger_active"),
        schema_fields: &["process_uuid", "session_id", "engine_kind", "status"],
        cli_flag: None,
        description: "Read active process ownership rows through the in-process InspectorReadV1 trait.",
        expected_input: "No input.",
        expected_output: "InspectorReadV1 ProcessRow JSON for currently running owned processes.",
        common_errors: &[
            "No active processes",
            "process ledger writer has not emitted START evidence",
        ],
        recovery_steps: &[
            "Inspect session state and EventLedger tail",
            "Use process reclaim surfaces if stale process rows remain",
        ],
    },
    CommandReference {
        id: "kernel_inspector_trace_projection",
        name: "kernel_inspector_trace_projection",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.trace_projection"),
        tauri_command: Some("kernel_inspector_trace_projection"),
        schema_fields: &[
            "session_id",
            "opened_at",
            "closed_at",
            "what_task",
            "what_context",
            "what_returns",
            "what_tool_calls",
            "what_artifacts",
            "what_validation",
            "what_promotion",
        ],
        cli_flag: None,
        description: "Read the HBR-VIS-004 session TraceProjection through the in-process InspectorReadV1 trait.",
        expected_input: "A SessionId for the governed model session.",
        expected_output: "InspectorReadV1 TraceProjection JSON or null when the session has no durable trace events.",
        common_errors: &[
            "Unknown session_id",
            "session has no durable EventLedger rows",
        ],
        recovery_steps: &[
            "Call kernel_inspector_event_ledger_tail to confirm events exist",
            "Use the HTTP /inspector/v1/trace/{session_id} route only when in-process IPC is unavailable",
        ],
    },
    CommandReference {
        id: "kernel_inspector_loaded_models",
        name: "kernel_inspector_loaded_models",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.inspector.loaded_models"),
        tauri_command: Some("kernel_inspector_loaded_models"),
        schema_fields: &["model_id", "adapter_id", "process_uuid", "loaded_at_utc"],
        cli_flag: None,
        description: "Read loaded model rows through the in-process InspectorReadV1 trait.",
        expected_input: "No input.",
        expected_output: "InspectorReadV1 ModelLoadedRow JSON for local or registered model adapters.",
        common_errors: &[
            "No model is loaded",
            "model runtime has not registered an adapter row",
        ],
        recovery_steps: &[
            "Register or load a model before expecting rows",
            "Inspect process ledger rows for the backing model process",
        ],
    },
    CommandReference {
        id: "inspector_replay_drive",
        name: "inspector_replay_drive",
        status: CommandStatus::Wired,
        ipc_channel: Some("/inspector/v1/replay-drive"),
        tauri_command: None,
        schema_fields: &[
            "action_id",
            "envelope",
            "schema_id",
            "signer",
            "signature",
            "write_box",
            "event_type",
        ],
        cli_flag: None,
        description: "POST the only inspector-plane mutation path through KernelActionCatalogV1 plus a verified WriteBoxV1 envelope.",
        expected_input: "JSON body with exactly action_id and envelope. Any extra or missing top-level field is a forbidden parallel-mutation attempt.",
        expected_output: "ReplayDriveResponse with dispatched status, write_box_id, result_schema_id, and INSPECTOR_REPLAY_DRIVE EventLedger receipt metadata.",
        common_errors: &[
            "Malformed JSON",
            "forbidden body shape",
            "invalid WriteBoxV1 envelope signature",
            "unknown KernelActionCatalogV1 action_id",
        ],
        recovery_steps: &[
            "Send only { action_id, envelope }",
            "Regenerate the envelope signature from the WriteBoxV1 payload",
            "Check the action catalog before retrying",
        ],
    },
    CommandReference {
        id: "swarm_harness_run",
        name: "swarm_harness_run",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &[
            "scenario_id",
            "n",
            "sessions",
            "contention_events",
            "ledger_overflow_count",
        ],
        cli_flag: None,
        description: "Run a bounded multi-agent harness scenario through the shared ScenarioRegistry and return observable session evidence.",
        expected_input: "A registered scenario_id and positive session count n.",
        expected_output: "SwarmReport with per-session results, ProcessLedger START/STOP rows, contention events, and ledger overflow count.",
        common_errors: &[
            "Unknown scenario_id",
            "n is zero",
            "ProcessLedger writer channel saturated",
        ],
        recovery_steps: &[
            "Call the registry-backed n8-perf, session-cancel, or lease-contention scenario id",
            "Reduce n if host capacity is limited",
            "Inspect ledger_overflow_count before retrying",
        ],
    },
    CommandReference {
        id: "handshake_swarm_cli",
        name: "handshake-swarm",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &["scenario_id", "n", "report_path"],
        cli_flag: Some("--scenario"),
        description: "Command-line entrypoint for the KERNEL-004 swarm harness; runs registered scenarios without app-runtime.",
        expected_input: "`handshake-swarm --scenario <n8-perf|session-cancel|lease-contention> --n <count> [--report <path>]`.",
        expected_output: "SwarmReport JSON on stdout, or a JSON receipt containing report_path when --report is provided.",
        common_errors: &[
            "Missing --scenario",
            "Missing --n",
            "Unknown scenario id",
            "Report path parent cannot be created",
        ],
        recovery_steps: &[
            "Run with --help to inspect syntax",
            "Use one of the documented scenario ids",
            "Write reports under the configured artifact root",
        ],
    },
    CommandReference {
        id: "kernel_swarm_run",
        name: "kernel_swarm_run",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.swarm.run"),
        tauri_command: Some("kernel_swarm_run"),
        schema_fields: &["scenario_id", "n", "sessions", "ledger_overflow_count"],
        cli_flag: None,
        description: "Debug-build Tauri IPC bridge that launches the swarm harness from Diagnostics-panel tooling through kernel.swarm.run.",
        expected_input: "JSON arguments with scenario_id and positive n; available only in debug builds compiled with feature swarm_ipc.",
        expected_output: "SwarmReport JSON matching the handshake-swarm CLI output shape.",
        common_errors: &[
            "App not compiled with swarm_ipc",
            "Release build omitted the command",
            "Unknown scenario_id",
            "n is zero",
        ],
        recovery_steps: &[
            "Rebuild the Tauri app in debug mode with --features swarm_ipc",
            "Use handshake-swarm CLI when IPC is unavailable",
            "Retry with n8-perf, session-cancel, or lease-contention",
        ],
    },
    CommandReference {
        id: "swarm_scenario_n8_perf",
        name: "n8-perf",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &["scenario_id", "n", "sessions"],
        cli_flag: Some("--scenario"),
        description: "n8-perf scenario: run high-volume catalog-backed mutation steps for each requested swarm session.",
        expected_input: "scenario_id n8-perf and positive n; canonical proof uses n=8 with 100 mutations per session.",
        expected_output: "SwarmReport with 100 completed catalog mutation steps per session and zero ledger overflow for healthy runs.",
        common_errors: &[
            "Host too slow for high-volume proof",
            "Unknown action catalog id",
        ],
        recovery_steps: &[
            "Start with --n 2 for smoke testing",
            "Use the hbr-swarm-n8 proof for the full HBR-SWARM evidence floor",
        ],
    },
    CommandReference {
        id: "swarm_scenario_session_cancel",
        name: "session-cancel",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &["scenario_id", "n", "sessions"],
        cli_flag: Some("--scenario"),
        description: "session-cancel scenario: exercise cancellation propagation through the ProcessLedger reclaim seam.",
        expected_input: "scenario_id session-cancel and positive n.",
        expected_output: "SwarmReport with each session completing an OperatorCancel reclaim step and closing with START/STOP process rows.",
        common_errors: &[
            "Reclaim trigger missing from scenario steps",
            "ProcessLedger STOP evidence absent",
        ],
        recovery_steps: &[
            "Inspect per-session reclaim_triggers",
            "Run process_ledger_reclaim_tests if STOP evidence is missing",
        ],
    },
    CommandReference {
        id: "swarm_scenario_lease_contention",
        name: "lease-contention",
        status: CommandStatus::Wired,
        ipc_channel: None,
        tauri_command: None,
        schema_fields: &["scenario_id", "n", "sessions"],
        cli_flag: Some("--scenario"),
        description: "lease-contention scenario: make every requested session target the shared lease workspace through the catalog lease action.",
        expected_input: "scenario_id lease-contention and positive n.",
        expected_output: "SwarmReport with shared-resource mutation attempts, inspector reads, and closed sessions for contention debugging.",
        common_errors: &[
            "Lease action catalog entry missing",
            "Shared workspace evidence is ambiguous",
        ],
        recovery_steps: &[
            "Verify kernel.role_mailbox_claim_lease.project exists in KernelActionCatalogV1",
            "Use per-session envelope refs to trace the contested resource",
        ],
    },
    CommandReference {
        id: "sandbox_adapter_run",
        name: "sandbox_adapter_run",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.sandbox.run"),
        tauri_command: Some("sandbox_adapter_run"),
        schema_fields: &[
            "adapter_id",
            "workspace_ref",
            "command_descriptor",
            "process_uuid",
        ],
        cli_flag: None,
        description: "Run model-written code or validation work inside the selected SandboxAdapter.",
        expected_input: "Adapter id, workspace ref, command descriptor, and ownership context.",
        expected_output: "Sandbox run result with process ledger references and denial evidence when blocked.",
        common_errors: &[
            "Adapter unavailable",
            "command descriptor requests undeclared filesystem or network access",
        ],
        recovery_steps: &[
            "Check sandbox_adapter_health",
            "Repair the command descriptor allowlist and retry",
        ],
    },
    CommandReference {
        id: "sandbox_adapter_health",
        name: "sandbox_adapter_health",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.sandbox.health"),
        tauri_command: Some("sandbox_adapter_health"),
        schema_fields: &["adapter_id", "availability", "reason", "host_capabilities"],
        cli_flag: None,
        description: "Report adapter availability and host capability gaps before a sandbox run starts.",
        expected_input: "Optional adapter id filter.",
        expected_output: "Health rows for WSL2 Podman, Windows native jail, Docker compatibility, and future adapters.",
        common_errors: &[
            "Host capability probe failed",
            "adapter is intentionally compatibility-only",
        ],
        recovery_steps: &[
            "Select an available adapter",
            "Use Docker only when explicitly opted in",
        ],
    },
    CommandReference {
        id: "model_runtime_generate",
        name: "model_runtime_generate",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.model_runtime.generate"),
        tauri_command: Some("model_runtime_generate"),
        schema_fields: &[
            "model_id",
            "prompt",
            "runtime_adapter",
            "generation_options",
            "process_uuid",
        ],
        cli_flag: None,
        description: "Generate text through the bound local ModelRuntime adapter.",
        expected_input: "Model id, prompt, and generation options.",
        expected_output: "Generated text plus runtime metrics, process ledger refs, and cache metadata.",
        common_errors: &[
            "Model not loaded",
            "runtime adapter does not support requested technique",
        ],
        recovery_steps: &[
            "Register or load the model",
            "Disable unsupported inference-lab toggles",
        ],
    },
    CommandReference {
        id: "model_runtime_register_model",
        name: "model_runtime_register_model",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.model_runtime.register_model"),
        tauri_command: None,
        schema_fields: &[
            "model_id",
            "artifact_path",
            "sha256",
            "adapter_kind",
            "capabilities",
        ],
        cli_flag: None,
        description: "Catalog-only governed action for registering a local model artifact with immutable adapter binding and capability metadata.",
        expected_input: "Artifact path, sha256, adapter kind, and capability declaration.",
        expected_output: "Model registry entry available to runtime and inference-lab surfaces after the governed action is wired.",
        common_errors: &[
            "Artifact hash mismatch",
            "adapter kind unsupported for artifact format",
        ],
        recovery_steps: &[
            "Recompute sha256",
            "Choose LlamaCppRuntime for GGUF or CandleRuntime for safetensors where supported",
            "Use catalog action kernel.model_runtime.register_model rather than a Tauri command until the IPC surface is implemented",
        ],
    },
    CommandReference {
        id: "inference_lab_apply_technique",
        name: "inference_lab_apply_technique",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.inference_lab.apply_technique"),
        tauri_command: Some("inference_lab_apply_technique"),
        schema_fields: &["technique_id", "enabled", "parameters", "model_id"],
        cli_flag: None,
        description: "Apply a supported inference technique such as LoRA, KV cache controls, steering vectors, or speculative decoding.",
        expected_input: "Technique id, model id, enabled flag, and technique parameters.",
        expected_output: "Updated runtime configuration or a typed unsupported-technique failure.",
        common_errors: &[
            "Technique unsupported by selected adapter",
            "parameter range invalid",
        ],
        recovery_steps: &[
            "Inspect model capabilities",
            "Reset the technique to its default parameters",
        ],
    },
    CommandReference {
        id: "memory_capsule_build",
        name: "memory_capsule_build",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.memory_capsule.build"),
        tauri_command: Some("memory_capsule_build"),
        schema_fields: &["task_kind", "budget_tokens", "capsule_refs", "audit_ref"],
        cli_flag: None,
        description: "Build a bounded memory capsule for a task from approved retrieval sources.",
        expected_input: "Task kind, token budget, and retrieval policy parameters.",
        expected_output: "Memory capsule artifact and audit reference.",
        common_errors: &[
            "Capsule exceeds token budget",
            "retrieval policy returns no eligible sources",
        ],
        recovery_steps: &[
            "Lower top-k or capsule size",
            "Inspect retrieval audit refs",
        ],
    },
    CommandReference {
        id: "memory_calibration_snapshot",
        name: "kernel_memory_calibration_snapshot",
        status: CommandStatus::Wired,
        ipc_channel: Some("kernel.memory_calibration.snapshot"),
        tauri_command: Some("kernel_memory_calibration_snapshot"),
        schema_fields: &[
            "bloat",
            "stale_dominance",
            "trust_drift",
            "embedding_gap",
            "degradation_rate",
            "hygiene_lag",
            "signal_errors",
        ],
        cli_flag: None,
        description: "Return the read-only FEMS calibration snapshot for operator and model diagnostics.",
        expected_input: "No input.",
        expected_output: "CalibrationSnapshot with six typed signal values, thresholds, timestamps, details, and per-signal source errors.",
        common_errors: &[
            "Postgres memory calibration state unavailable",
            "invalid calibration threshold",
            "calibration source IO failed",
        ],
        recovery_steps: &[
            "Check DATABASE_URL and Postgres availability",
            "Inspect signal_errors to identify which collector failed",
            "Run calibration_tests for threshold and snapshot-shape regression coverage",
        ],
    },
    CommandReference {
        id: "self_improvement_run_iteration",
        name: "self_improvement_run_iteration",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.self_improvement.run_iteration"),
        tauri_command: Some("self_improvement_run_iteration"),
        schema_fields: &[
            "corpus_id",
            "dev_score",
            "holdout_score",
            "promotion_decision",
        ],
        cli_flag: None,
        description: "Run one bounded self-improvement iteration against the fixed HBR corpus.",
        expected_input: "Corpus id, editable surface parameters, and promotion thresholds.",
        expected_output: "Iteration report with dev and holdout metrics plus promotion decision.",
        common_errors: &[
            "Goodhart sentinel paused the loop",
            "holdout score below promotion floor",
        ],
        recovery_steps: &[
            "Review promotion gate evidence",
            "Adjust only approved retrieval or manual parameters",
        ],
    },
    CommandReference {
        id: "distillation_candidate_review",
        name: "distillation_candidate_review",
        status: CommandStatus::Planned,
        ipc_channel: Some("kernel.distillation.review_candidate"),
        tauri_command: Some("distillation_candidate_review"),
        schema_fields: &[
            "candidate_id",
            "license_tags",
            "pii_scan",
            "operator_decision",
        ],
        cli_flag: None,
        description: "Review a distillation candidate before promotion into a model runtime surface.",
        expected_input: "Candidate id and review decision payload.",
        expected_output: "Promotion, rejection, or remediation receipt with review evidence refs.",
        common_errors: &[
            "PII scan failed",
            "license tag missing",
            "operator decision absent",
        ],
        recovery_steps: &[
            "Run content review again",
            "Attach required provenance and operator decision refs",
        ],
    },
];

pub static SAFETY_CONSTRAINTS: &[ManualSafetyConstraint] = &[
    ManualSafetyConstraint {
        id: "manual_same_commit_currency",
        constraint_text: "HBR-MAN-001 requires every wired surface diff to update ModelManual content and bump MANUAL_VERSION in the same commit.",
        enforcement_point: "hbr-man-001 paired-diff check",
    },
    ManualSafetyConstraint {
        id: "manual_no_context_operation",
        constraint_text: "HBR-MAN-002 requires a no-context model to operate core workflows from ModelManual alone without chat history.",
        enforcement_point: "manual no-context harness",
    },
    ManualSafetyConstraint {
        id: "quiet_model_operation",
        constraint_text: "HBR-QUIET rules require diagnostics, GUI testing, and model-driven interaction to stay non-intrusive and observable.",
        enforcement_point: "visual debugging and process-ledger checks",
    },
    ManualSafetyConstraint {
        id: "typed_hbr_receipts",
        constraint_text: "HBR violations route through typed HBR_VIOLATION receipts; notes may add context but never carry routing authority.",
        enforcement_point: "hbr-violation.schema.json",
    },
];

pub static WORKFLOWS: &[ManualWorkflow] = &[
    ManualWorkflow {
        id: "startup",
        title: "Startup",
        prerequisites: &[
            "Open the active worktree",
            "Read local AGENTS.md and packet authority",
            "Confirm the active microtask claim",
        ],
        steps: &[
            "Read the ModelManual manifest through kernel.model_manual.get when the IPC bridge is available.",
            "List command references and identify which feature group owns the task area.",
            "Run the required proof commands from the active microtask before claiming completion.",
        ],
        expected_outcome: "The model knows the command surface, safety constraints, and verification path without prior chat context.",
        failure_modes: &[
            "Manual IPC bridge not registered",
            "Command reference is planned and not yet callable",
        ],
    },
    ManualWorkflow {
        id: "governed_session_run",
        title: "Basic Governed Session Run",
        prerequisites: &[
            "Active work packet",
            "Claimed microtask",
            "Known proof commands",
        ],
        steps: &[
            "Use the feature group to find command references relevant to the microtask.",
            "Execute only wired commands unless a planned entry is explicitly being implemented.",
            "Emit typed receipts or events for HBR failures and rerun verification after repair.",
        ],
        expected_outcome: "The governed session completes with traceable evidence and no stale manual assumptions.",
        failure_modes: &[
            "HBR matrix row remains PENDING",
            "Evidence pointer cannot be resolved",
            "MANUAL_VERSION not bumped after a wired-surface diff",
        ],
    },
    ManualWorkflow {
        id: "diagnostics_panel_triage",
        title: "Diagnostics Panel Triage",
        prerequisites: &[
            "Diagnostics capture surface available",
            "Target app route or backend state selector",
        ],
        steps: &[
            "Capture a headless visual or backend snapshot without foreground focus.",
            "Inspect stable element ids, logs, traces, and process ledger refs.",
            "Attach screenshot, event, artifact, or receipt evidence to the relevant HBR row.",
        ],
        expected_outcome: "A no-context model can isolate UI or runtime failures without screen-scraping guesses.",
        failure_modes: &[
            "Capture attempts to open a foreground window",
            "Snapshot lacks stable identifiers",
            "Process ledger START/STOP evidence is missing",
        ],
    },
];
